# Generated by Django 3.0.3 on 2020-04-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('poster', models.ImageField(upload_to='img')),
                ('director', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
            ],
            options={
                'verbose_name': 'movie',
            },
        ),
    ]
