# Generated by Django 3.0.3 on 2020-04-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pwd', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=11)),
                ('sex', models.IntegerField(choices=[(0, 'M'), (1, 'N')], default=0)),
                ('icon', models.ImageField(default='icon/default.jpg', upload_to='icon')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'db_table': 'movie_user',
            },
        ),
    ]
